version: "3"
networks:
  brusaalves-nifi:
    driver: bridge
    ipam:
      config:
        - subnet: 150.1.0.0/16
services:
  nifi:
    container_name: brusaalves-nifi
    image: apache/nifi:1.12.0
    networks:
      brusaalves-nifi:
        ipv4_address: 150.1.1.10
    ports:
      - 8080:8080
    environment:
      HOSTNAME: 0.0.0.0
      NIFI_VARIABLE_REGISTRY_PROPERTIES: ./conf/args.properties
    volumes:
      # Project sources (configurations, flows and packages)
      - ./app/nifi/src/conf:/opt/nifi/nifi-current/conf
      - ./app/nifi/src/flow:/opt/nifi/nifi-current/flow
      - ./app/nifi/src/lib:/opt/nifi/nifi-current/lib/custom
      # NiFi resources
      - ./app/nifi/res/content_repository:/opt/nifi/nifi-current/content_repository
      - ./app/nifi/res/database_repository:/opt/nifi/nifi-current/database_repository
      - ./app/nifi/res/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./app/nifi/res/logs:/opt/nifi/nifi-current/logs
      - ./app/nifi/res/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./app/nifi/res/state:/opt/nifi/nifi-current/state