version: '3'
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 150.1.0.0/16
services:
  nifi:
    container_name: nifi
    image: apache/nifi:1.9.0
    networks:
      main:
        ipv4_address: 150.1.1.10
    ports:
      - 80:8080
    volumes:
      # transitory NiFi data
      - ./../app/res/content_repository:/opt/nifi/nifi-current/content_repository
      - ./../app/res/database_repository:/opt/nifi/nifi-current/database_repository
      - ./../app/res/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./../app/res/logs:/opt/nifi/nifi-current/logs
      - ./../app/res/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./../app/res/state:/opt/nifi/nifi-current/state
      # parameterizable NiFi files
      - ./../app/src/conf:/opt/nifi/nifi-current/conf
      - ./../app/src/package/custom:/opt/nifi/nifi-current/extensions