version: '3'
networks:
  nifi:
    driver: bridge
    ipam:
      config:
        - subnet: $ENV_SUBNET
services:
  nifi:
    container_name: nifi
    build:
      context: ./nifi
      args:
        IMAGE: $NIFI_IMAGE
    image: brusalves_$NIFI_IMAGE
    networks:
      nifi:
        ipv4_address: $NIFI_IP
    ports:
      - $NIFI_ACCESS_PORT:$NIFI_PORT
    environment:
      - NIFI_WEB_HTTP_PORT=$NIFI_PORT
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=/opt/nifi/nifi-current/conf/custom/args.properties
    volumes:
      # transitory NiFi data
      - ./../app/nifi/res/content_repository:/opt/nifi/nifi-current/content_repository
      - ./../app/nifi/res/database_repository:/opt/nifi/nifi-current/database_repository
      - ./../app/nifi/res/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./../app/nifi/res/logs:/opt/nifi/nifi-current/logs
      - ./../app/nifi/res/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./../app/nifi/res/state:/opt/nifi/nifi-current/state
      # NiFi project files (configurations and packages)
      - ./../app/nifi/src/conf:/opt/nifi/nifi-current/conf/custom
      - ./../app/nifi/src/lib:/opt/nifi/nifi-current/lib/custom
      - ./../app/nifi/src/flow:/opt/nifi/nifi-current/flow